### ISSUE TITLE
Travel-CI bug of building node c addons

### ISSUE THREAD

**Issue by willworks** [willworks/blog#8]
### Description

```

make: Entering directory `/home/travis/build/willworks/nodec/build'
  CXX(target) Release/obj.target/main/src/main.o
In file included from /home/travis/.node-gyp/4.5.0/include/node/node.h:42:0,
                 from ../src/main.cc:1:
/home/travis/.node-gyp/4.5.0/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.5.0/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.5.0/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
../src/main.cc:14:15: error: ‘v8::Handle’ has not been declared
../src/main.cc: In function ‘void main::ARR(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/main.cc:69:19: warning: unused variable ‘isolate’ [-Wunused-variable]
make: *** [Release/obj.target/main/src/main.o] Error 1
make: Leaving directory `/home/travis/build/willworks/nodec/build'

```

### Solution

```

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

```
